### ISSUE TITLE
The AspNetCoreExample example does not have very much "example content"

### ISSUE THREAD

**Issue by leftler** [unitycontainer/examples#3]
This example project https://github.com/unitycontainer/examples/tree/master/src/AspNetCoreExample is extremely bare bones. The only two things I can see is it adds is
https://github.com/unitycontainer/examples/blob/6b5c7c290677c5c533e999f309ed0abc8ef953ae/src/AspNetCoreExample/Program.cs#L14-L18
and
https://github.com/unitycontainer/examples/blob/6b5c7c290677c5c533e999f309ed0abc8ef953ae/src/AspNetCoreExample/Startup.cs#L15-L17
which it then does nothing with `_container`.

Please update the example showing at minimum how to load the unity configuration from a `appsettings.json` file.

**Comment by ENikS** [comment]
Would you like to help and contribute some time to do it properly?
